steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - cicdcf #function name
  - --source=. #source location
  - --trigger-http
  - --runtime=python38
  - --region=us-central1
  - --entry-point=hello_world
